name: .NET Build, Pack & Publish

on: 
  push:
    branches:
      - main
  workflow_dispatch:

env:
  YumeChan_PluginsLocation: build

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full git history is available for NBGV
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: .NET Build & Pack
        run: dotnet build -c release -o "publish"
        
      - name: Upload dotnet build
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build-release
          path: "build"
